### ISSUE TITLE
Feature request: set the downloaded article's state to archived

### ISSUE THREAD

**Issue by zsoltika** [agrmohit/omnivore-epub#2]
I love your script and swapping out Instapaper for me. 

It would be great if after successfully downloading and converting to epub all the downloaded articles would be archived (now I'm doing this manually).

**Comment by zsoltika** [comment]
Also if it's possible download the oldest saved articles first?

**Comment by agrmohit** [comment]
Glad to hear you love it. I know very little about graphql as this script is mostly taken from a gist created by someone else. But I will try to see if I can add auto archiving as an option.

**Comment by jsanz** [comment]
> Also if it's possible download the oldest saved articles first?

Change this setting in the configuration:

```json
  "searchQuery": "sort:saved-desc",
```

to 

```json
  "searchQuery": "sort:saved-asc",
```

That should do the trick

**Comment by kevinschaul** [comment]
I've been trying something similar -- an option to add a label to each article after it gets saved as an epub. (Then you could modify your search to exclude that label.) But I am struggling with graphql.

I added this to my config:

```
  "addLabelToSavedArticles": { "name": "sent-to-epub", "color": "#cccccc", "description": "Already sent to epub" },
```

I thought adding this would work, inside the loop through `articles.edges`:
```
      if (config.addLabelToSavedArticles) {
        const SET_LABELS_MUTATION = `
          mutation SetLabels($input: SetLabelsInput!) {
            setLabels(input: $input) {
              __typename
              ... on SetLabelsSuccess {
                labels
              }
              ... on SetLabelsError {
                errorCodes
              }
            }
          }
        `;
        article.labels.push(config.addLabelToSavedArticles)

        const input = {
          pageId: article.id,
          labels: article.labels
        }
        console.log(input)
        const { data: setLabelsData, error: setLabelsError } = await omnivore.client
          .mutation(SET_LABELS_MUTATION, { input })
          .toPromise();
        console.log(setLabelsData)
        console.log(setLabelsError)
```

But I just get an unhelpful error:

```
CombinedError: [GraphQL] Unexpected server error
    at makeResult (file:///home/kevin/.cache/deno/npm/registry.npmjs.org/@urql/core/4.3.0/dist/urql-core-chunk.js:381:43)
    at fetchOperation (file:///home/kevin/.cache/deno/npm/registry.npmjs.org/@urql/core/4.3.0/dist/urql-core-chunk.js:812:80)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async file:///home/kevin/.cache/deno/npm/registry.npmjs.org/wonka/6.3.4/dist/wonka.js:346:20 {
  name: "CombinedError",
  graphQLErrors: [
    GraphQLError: Unexpected server error
    at rehydrateGraphQlError (file:///home/kevin/.cache/deno/npm/registry.npmjs.org/@urql/core/4.3.0/dist/urql-core-chunk.js:19:12)
    at Array.map (<anonymous>)
    at new CombinedError (file:///home/kevin/.cache/deno/npm/registry.npmjs.org/@urql/core/4.3.0/dist/urql-core-chunk.js:74:63)
    at makeResult (file:///home/kevin/.cache/deno/npm/registry.npmjs.org/@urql/core/4.3.0/dist/urql-core-chunk.js:381:43)
    at fetchOperation (file:///home/kevin/.cache/deno/npm/registry.npmjs.org/@urql/core/4.3.0/dist/urql-core-chunk.js:812:80)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async file:///home/kevin/.cache/deno/npm/registry.npmjs.org/wonka/6.3.4/dist/wonka.js:346:20 {
      name: "GraphQLError",
      originalError: { message: "Unexpected server error" },
      extensions: {}
    }
  ],
```

It feels so close, but I just can't figure out how to get it to work.
